"""Finite molecular cluster carved from a periodic crystal.

This module defines the two tightly coupled objects produced and
consumed by :mod:`molcrys_kit.operations.cluster`:

* :class:`ClusterProvenance` -- a frozen dataclass capturing the
  audit trail of a single carve (seed indices, kept atoms, cut
  bonds, cap H bookkeeping, freeze convention, citation reference,
  ...).  Mirrors the design of
  :class:`molcrys_kit.analysis.disorder.provenance.DisorderProvenance`
  and supports ``to_dict`` / ``from_dict`` JSON-sidecar round-trip.
  The sidecar travels with the XYZ output so downstream Gaussian /
  ORCA-input scripts (outside this package) can pick up frozen-atom
  indices, cap-atom indices, and the kept-to-parent index map
  without re-running the carver.

* :class:`CrystalCluster` -- a :class:`CrystalMolecule` that always
  carries ``pbc=False`` and that owns one
  :class:`ClusterProvenance` plus ``frozen_local_indices`` and
  ``cap_local_indices`` lists.

The two are inlined in the same module because ``CrystalCluster``
is the *only* consumer of ``ClusterProvenance``; the dataclass has
no independent life cycle.  Keeping them together removes a layer
of cross-package import (``structures`` -> ``analysis``) for what is
purely structural metadata.

The class deliberately stays at the atom + bond level; it does not
introduce any domain-specific ontology (SBU / linker / pore for MOFs,
ring / channel for zeolites, vertex / strut for COFs, ...).  Callers
wanting such typing should layer it on top of the existing
``ChemicalEnvironment`` analyser.
"""

from __future__ import annotations

from dataclasses import dataclass, field, asdict
from typing import Any, Dict, List, Optional, Tuple

import numpy as np

from .molecule import CrystalMolecule


@dataclass(frozen=True)
class ClusterProvenance:
    """Audit trail for a single carved cluster.

    Attributes
    ----------
    mode : str
        ``"bond_shells"`` (chemistry-aware carving) or ``"rcut"`` (radial
        diagnostic carving).
    seed_global_indices : List[int]
        Global atom indices in the parent ``MolecularCrystal.to_ase()`` that
        seeded this cluster (after seed-merge auto-grouping).
    rcut_A : Optional[float]
        Radial cutoff in Angstrom, when ``mode == "rcut"``.  ``None`` for
        bond-shells mode.
    max_atoms : Optional[int]
        Hard topology-preserving BFS safety cap used by ``bond_shells``.
        ``None`` means disabled, and is always used for radial mode.
    kept_global_indices : List[int]
        Global parent-atom indices retained in the cluster.  Cap H atoms
        do not appear here (they have no parent atom).
    cut_bonds : List[Tuple[int, int]]
        For each dangling bond cut during carving, ``(kept_global_idx,
        dropped_global_idx)``.  The same length as ``cap_local_indices``.
    cut_cc_bonds_requested : List[Tuple[int, int]]
        User-requested parent-index C-C truncation bonds, normalized and
        sorted as undirected parent edges.
    cut_cc_bonds_applied : List[Tuple[int, int]]
        Requested C-C truncation bonds that actually became cluster
        boundaries, recorded as ``(kept_global_idx, dropped_global_idx)``.
    metal_boundary_cuts : List[Tuple[int, int]]
        Subset of ``cut_bonds`` generated by ``stop_at_non_seed_metals``.
    loop_cuts : List[Tuple[int, int]]
        Parent edges that close a topologically nontrivial loop crossing a
        periodic-cell face.  Both endpoints stay in ``kept_global_indices``
        but the bond cannot be realized in a single non-periodic frame, so
        it is broken and capped with H on *both* sides.  Each pair is
        recorded once (sorted as ``(min, max)``); the two corresponding
        caps appear in ``cut_bonds`` as ``(a, b)`` and ``(b, a)``.
    cap_local_indices : List[int]
        Indices, in the emitted cluster's atom list, of the H atoms that
        cap the dangling bonds.  May be shorter than ``cut_bonds`` when
        several cuts share the same non-C keeper atom and have been
        chemistry-aware deduplicated into a single cap (a mu-N bridging
        two Zn outside the seed group receives one cap, not two).
    cap_keeper_global_indices : List[int]
        For each entry in ``cap_local_indices``, the global parent-atom
        index of the keeper atom that the cap H is bonded to.  Use this
        to associate caps with their parent atoms after deduplication.
    frozen_local_indices : List[int]
        Indices, in the emitted cluster's atom list, of atoms to be held
        fixed during QM geometry optimisation.  See ``freeze_shell``
        semantics in :func:`molcrys_kit.operations.cluster.ClusterCarver`.
    freeze_shell : int
        Which freeze convention was used: ``0`` = none, ``1`` = caps +
        the heavy atom they replace, ``2`` = shell-1 plus one more layer
        of heavy atoms inward.
    cap_distance_A : float or None
        Uniform cap-distance override (Angstrom) supplied by the caller,
        or ``None`` when the carver looked up per-element X-H bond
        lengths from the ``cap_bond_lengths_A`` table.
    cap_bond_lengths_A : dict[str, float]
        Element-keyed X-H bond lengths consulted by the carver (typically
        the shared ``molcrys_kit.constants.config.BOND_LENGTHS`` table
        plus any user overrides).  Recorded so the sidecar JSON is
        self-describing even when the global table changes between MCK
        versions.
    cap_distances_used_A : list[float]
        Per-cap distance actually applied, in the same order as
        ``cap_local_indices`` / ``cut_bonds``.
    seed_merge_radius_A : float
        Distance threshold (Angstrom) under which adjacent metal seeds
        were auto-grouped into one cluster.
    parent_label : Optional[str]
        Free-text label of the parent structure (e.g. the source CIF
        path).  Not used by the algorithm; for human bookkeeping.
    kind : str
        Carve-strategy tag distinguishing this cluster from clusters
        produced by other future carvers.  The current
        :class:`molcrys_kit.operations.cluster.ClusterCarver` produces
        ``"coordination"`` clusters (metal seed + ligand-complete BFS
        + anion-group capping at the metal boundary) -- the cluster
        in the literature sense of "coordination cluster / SBU
        environment", not the supramolecular sense of "weak-interaction
        packing cluster".  A future pi-stack or H-bond carver would
        emit ``kind="packing"``; this field gives downstream consumers
        a single tag to discriminate without having to introspect the
        rest of the provenance.  Recorded in the sidecar JSON so the
        cluster's scope is self-describing.
    convention_reference : str
        Free-text citation block describing the published convention
        that motivated the specific parameter choices for this carve
        (manual C-C truncation, ``freeze_shell``, ``cap_distance`` override, cap
        bond length overrides).  The default points at the canonical
        cap-distance / shell-1 / shell-2 / rcut-convergence references
        in the QM-cluster literature (see
        :mod:`molcrys_kit.operations.cluster`); callers are encouraged
        to override it with the DOI(s) appropriate to their own system
        so the sidecar JSON is fully self-documenting.
    """

    mode: str
    seed_global_indices: List[int]
    rcut_A: Optional[float]
    max_atoms: Optional[int]
    kept_global_indices: List[int]
    cut_bonds: List[Tuple[int, int]]
    cut_cc_bonds_requested: List[Tuple[int, int]]
    cut_cc_bonds_applied: List[Tuple[int, int]]
    metal_boundary_cuts: List[Tuple[int, int]]
    cap_local_indices: List[int]
    frozen_local_indices: List[int]
    freeze_shell: int
    loop_cuts: List[Tuple[int, int]] = field(default_factory=list)
    cap_keeper_global_indices: List[int] = field(default_factory=list)
    cap_distance_A: Optional[float] = None
    cap_bond_lengths_A: Dict[str, float] = field(default_factory=dict)
    cap_distances_used_A: List[float] = field(default_factory=list)
    seed_merge_radius_A: float = 0.0
    parent_label: Optional[str] = None
    kind: str = "coordination"
    convention_reference: str = (
        "Default QM-cluster convention: H caps along the cut bond at the "
        "element-specific X-H length from BOND_LENGTHS (Wu/Gagliardi/Truhlar "
        "PCCP 2018, 10.1039/c7cp06751h; cap-vs-periodic benchmark in "
        "Beyzavi et al. JACS 2014, 10.1021/ja508626n); shell-1 freeze = "
        "cap H + cut-side keeper (Wu/Truhlar PCCP 2018; Vitillo et al. "
        "JPCC 2023, 10.1021/acs.jpcc.3c06423); shell-2 freeze adds one "
        "heavy-atom layer inward (Gaggioli et al. Chem Sci 2020, "
        "10.1039/d0sc02136a); rcut diagnostic follows Migues/Auerbach "
        "JPCC 2018, 10.1021/acs.jpcc.8b08684 (delta-cluster convergence "
        "test).  Callers should override with their system-specific "
        "citation."
    )

    def to_dict(self) -> Dict[str, Any]:
        """Serialize to a plain-dict (JSON-ready) representation.

        Tuples become lists; the dataclass field names are preserved.
        """
        payload = asdict(self)
        # Tuples in cut_bonds become lists under asdict already; ensure
        # the integer values are plain ints (not numpy) so json.dumps works.
        payload["seed_global_indices"] = [int(i) for i in payload["seed_global_indices"]]
        payload["kept_global_indices"] = [int(i) for i in payload["kept_global_indices"]]
        payload["cap_local_indices"] = [int(i) for i in payload["cap_local_indices"]]
        payload["frozen_local_indices"] = [int(i) for i in payload["frozen_local_indices"]]
        payload["cut_bonds"] = [[int(a), int(b)] for a, b in payload["cut_bonds"]]
        payload["cut_cc_bonds_requested"] = [
            [int(a), int(b)] for a, b in payload.get("cut_cc_bonds_requested", [])
        ]
        payload["cut_cc_bonds_applied"] = [
            [int(a), int(b)] for a, b in payload.get("cut_cc_bonds_applied", [])
        ]
        payload["metal_boundary_cuts"] = [
            [int(a), int(b)] for a, b in payload.get("metal_boundary_cuts", [])
        ]
        payload["loop_cuts"] = [
            [int(a), int(b)] for a, b in payload.get("loop_cuts", [])
        ]
        payload["cap_keeper_global_indices"] = [
            int(g) for g in payload.get("cap_keeper_global_indices", [])
        ]
        if payload["rcut_A"] is not None:
            payload["rcut_A"] = float(payload["rcut_A"])
        if payload["max_atoms"] is not None:
            payload["max_atoms"] = int(payload["max_atoms"])
        payload["freeze_shell"] = int(payload["freeze_shell"])
        if payload["cap_distance_A"] is not None:
            payload["cap_distance_A"] = float(payload["cap_distance_A"])
        payload["cap_bond_lengths_A"] = {
            str(k): float(v) for k, v in payload.get("cap_bond_lengths_A", {}).items()
        }
        payload["cap_distances_used_A"] = [
            float(v) for v in payload.get("cap_distances_used_A", [])
        ]
        payload["seed_merge_radius_A"] = float(payload["seed_merge_radius_A"])
        payload["kind"] = str(payload.get("kind", "coordination"))
        return payload

    @classmethod
    def from_dict(cls, payload: Dict[str, Any]) -> "ClusterProvenance":
        """Inverse of :meth:`to_dict`.  Tuples are restored from list pairs."""
        cut_bonds: List[Tuple[int, int]] = [
            (int(a), int(b)) for a, b in payload.get("cut_bonds", [])
        ]
        cut_cc_bonds_requested: List[Tuple[int, int]] = [
            (int(a), int(b)) for a, b in payload.get("cut_cc_bonds_requested", [])
        ]
        cut_cc_bonds_applied: List[Tuple[int, int]] = [
            (int(a), int(b)) for a, b in payload.get("cut_cc_bonds_applied", [])
        ]
        metal_boundary_cuts: List[Tuple[int, int]] = [
            (int(a), int(b)) for a, b in payload.get("metal_boundary_cuts", [])
        ]
        loop_cuts: List[Tuple[int, int]] = [
            (int(a), int(b)) for a, b in payload.get("loop_cuts", [])
        ]
        cap_keeper_global_indices: List[int] = [
            int(g) for g in payload.get("cap_keeper_global_indices", [])
        ]
        kwargs = dict(payload)
        kwargs["cut_bonds"] = cut_bonds
        kwargs["cut_cc_bonds_requested"] = cut_cc_bonds_requested
        kwargs["cut_cc_bonds_applied"] = cut_cc_bonds_applied
        kwargs["metal_boundary_cuts"] = metal_boundary_cuts
        kwargs["loop_cuts"] = loop_cuts
        kwargs["cap_keeper_global_indices"] = cap_keeper_global_indices
        kwargs["seed_global_indices"] = [int(i) for i in payload["seed_global_indices"]]
        kwargs["kept_global_indices"] = [int(i) for i in payload["kept_global_indices"]]
        kwargs["cap_local_indices"] = [int(i) for i in payload["cap_local_indices"]]
        kwargs["frozen_local_indices"] = [int(i) for i in payload["frozen_local_indices"]]
        kwargs["cap_bond_lengths_A"] = {
            str(k): float(v)
            for k, v in payload.get("cap_bond_lengths_A", {}).items()
        }
        kwargs["cap_distances_used_A"] = [
            float(v) for v in payload.get("cap_distances_used_A", [])
        ]
        # Backward-compat: sidecars produced before the ``kind`` tag
        # was introduced default to coordination clusters (which is
        # what ClusterCarver always emitted historically).
        kwargs["kind"] = str(payload.get("kind", "coordination"))
        return cls(**kwargs)


class CrystalCluster(CrystalMolecule):
    """A non-periodic molecular cluster derived from a :class:`MolecularCrystal`.

    Parameters
    ----------
    atoms : ase.Atoms
        The cluster atoms with explicit Cartesian positions.  ``pbc`` is
        forced to ``False`` on construction.
    provenance : ClusterProvenance
        Audit trail describing the carve (see :class:`ClusterProvenance`
        in this module).
    frozen_local_indices : list[int]
        Local indices (into the emitted atom list) that downstream QM
        runs should hold fixed.  Stored as ``int`` tuple for immutability.
    cap_local_indices : list[int]
        Local indices of the H atoms that cap dangling bonds.
    parent_crystal : object, optional
        Reference to the parent crystal (matches ``CrystalMolecule.crystal``).
    """

    def __init__(
        self,
        atoms,
        provenance: ClusterProvenance,
        frozen_local_indices: Optional[List[int]] = None,
        cap_local_indices: Optional[List[int]] = None,
        parent_crystal=None,
    ):
        # Force pbc=False on the underlying Atoms before calling the parent
        # constructor; check_pbc=False prevents the unwrap pass since the
        # cluster is already contiguous in Cartesian space.
        atoms = atoms.copy()
        atoms.set_pbc(False)
        atoms.set_cell(np.zeros((3, 3)))
        super().__init__(atoms, crystal=parent_crystal, check_pbc=False)

        self._provenance = provenance
        self._frozen_local_indices = tuple(int(i) for i in (frozen_local_indices or []))
        self._cap_local_indices = tuple(int(i) for i in (cap_local_indices or []))

    @property
    def provenance(self) -> ClusterProvenance:
        return self._provenance

    @property
    def frozen_local_indices(self) -> List[int]:
        return list(self._frozen_local_indices)

    @property
    def cap_local_indices(self) -> List[int]:
        return list(self._cap_local_indices)

    def copy(self) -> "CrystalCluster":  # type: ignore[override]
        atoms_copy = CrystalMolecule.copy(self).to_ase()
        return CrystalCluster(
            atoms_copy,
            provenance=self._provenance,
            frozen_local_indices=list(self._frozen_local_indices),
            cap_local_indices=list(self._cap_local_indices),
            parent_crystal=self.crystal,
        )

    def __repr__(self) -> str:  # pragma: no cover - cosmetic
        return (
            f"CrystalCluster(formula='{self.get_chemical_formula()}', "
            f"atoms={len(self)}, frozen={len(self._frozen_local_indices)}, "
            f"caps={len(self._cap_local_indices)}, mode={self._provenance.mode})"
        )


__all__ = ["CrystalCluster", "ClusterProvenance"]
