"""Exact periodic-rank analysis for quotient chemical graphs.

A bond crossing a unit-cell face does not by itself make a molecule periodic:
it may merely unwrap one finite molecule. Periodicity is instead generated by
non-zero lattice translations accumulated around graph cycles. This module
computes those cycle translations and their exact rank in three dimensions.
"""

from __future__ import annotations

from dataclasses import dataclass

from .models import ChemicalBond, ImageShift


@dataclass(frozen=True)
class PeriodicTopology:
    """Translation subgroup generated by a connected quotient graph."""

    rank: int
    translation_generators: tuple[ImageShift, ...]

    def __post_init__(self) -> None:
        if self.rank not in {0, 1, 2, 3}:
            raise ValueError("periodic rank must be between zero and three")
        if len(self.translation_generators) != self.rank:
            raise ValueError("generator count must equal periodic rank")


def analyze_periodic_topology(
    atom_ids: tuple[str, ...],
    bonds: tuple[ChemicalBond, ...],
    *,
    periodic_axes: tuple[bool, bool, bool] = (True, True, True),
) -> PeriodicTopology:
    """Return the exact 0D--3D translation rank of a quotient graph.

    Tree-edge translations only choose contiguous images of graph vertices.
    Every non-tree edge contributes a closed-walk translation; the independent
    subset of those integer vectors defines the component dimension.
    """
    known = set(atom_ids)
    if any(bond.atom1_id not in known or bond.atom2_id not in known for bond in bonds):
        raise ValueError("bond endpoint is absent from atom_ids")
    if len(periodic_axes) != 3:
        raise ValueError("periodic_axes must contain three booleans")

    mask = tuple(int(value) for value in periodic_axes)
    adjacency: dict[str, list[tuple[str, ImageShift]]] = {
        atom_id: [] for atom_id in atom_ids
    }
    for bond in bonds:
        shift = tuple(
            int(value) * periodic for value, periodic in zip(bond.atom2_image_shift, mask)
        )
        reverse = tuple(-value for value in shift)
        adjacency[bond.atom1_id].append((bond.atom2_id, shift))
        adjacency[bond.atom2_id].append((bond.atom1_id, reverse))

    potentials: dict[str, ImageShift] = {}
    cycle_translations: set[ImageShift] = set()
    for root in atom_ids:
        if root in potentials:
            continue
        potentials[root] = (0, 0, 0)
        stack = [root]
        while stack:
            atom_id = stack.pop()
            for neighbor_id, shift in adjacency[atom_id]:
                proposed = tuple(
                    left + right for left, right in zip(potentials[atom_id], shift)
                )
                if neighbor_id not in potentials:
                    potentials[neighbor_id] = proposed
                    stack.append(neighbor_id)
                    continue
                residual = tuple(
                    left - right
                    for left, right in zip(proposed, potentials[neighbor_id])
                )
                canonical = _canonical_translation(residual)
                if canonical != (0, 0, 0):
                    cycle_translations.add(canonical)

    independent: list[ImageShift] = []
    for candidate in sorted(cycle_translations, key=_generator_sort_key):
        if _integer_rank((*independent, candidate)) > len(independent):
            independent.append(candidate)
        if len(independent) == 3:
            break
    return PeriodicTopology(len(independent), tuple(independent))


def _canonical_translation(vector) -> ImageShift:
    values = tuple(int(value) for value in vector)
    first_nonzero = next((value for value in values if value), 0)
    if first_nonzero < 0:
        return tuple(-value for value in values)
    return values


def _generator_sort_key(vector: ImageShift) -> tuple[int, int, int, int, int]:
    first_axis = next(index for index, value in enumerate(vector) if value)
    return (sum(value * value for value in vector), first_axis, *vector)


def _integer_rank(vectors: tuple[ImageShift, ...]) -> int:
    nonzero = [vector for vector in vectors if any(vector)]
    if not nonzero:
        return 0
    first = nonzero[0]
    second = next(
        (vector for vector in nonzero[1:] if any(_cross(first, vector))),
        None,
    )
    if second is None:
        return 1
    for third in nonzero[1:]:
        cross = _cross(second, third)
        determinant = sum(left * right for left, right in zip(first, cross))
        if determinant != 0:
            return 3
    return 2


def _cross(left: ImageShift, right: ImageShift) -> ImageShift:
    return (
        left[1] * right[2] - left[2] * right[1],
        left[2] * right[0] - left[0] * right[2],
        left[0] * right[1] - left[1] * right[0],
    )


__all__ = ["PeriodicTopology", "analyze_periodic_topology"]
